### ISSUE TITLE
Incompatibility with Kotlin plugins 

### ISSUE THREAD

**Issue by pintoso** [SteveTheEngineer/SS-Kotlin#1]
[Trhologram](https://github.com/Arasple/TrHologram) stops working completely when used with SS-Kotlin

LOG: [click here](https://paste.gg/p/anonymous/b13684061b23468aaae1f9a77a99233e)

How to reproduce:
1. 1.16.x paper server
2. install [Trhologram](https://www.spigotmc.org/resources/trhologram-1-9-1-16.75503) + [SS-FancyDrops](https://www.spigotmc.org/resources/steves-series-fancy-drops.68373) + [SS-Kotlin](https://www.spigotmc.org/resources/steves-series-kotlin.89347)

>>Idk the source of the problem so I opened the issue in both places
the issue in trhologram is [>HERE<](https://github.com/Arasple/TrHologram/issues/25)

**Comment by SteveTheEngineer** [comment]
Sorry it took so long to answer! This was not a problem on my side, the plugin's developer has since fixed the issue: https://github.com/Arasple/TrHologram/issues/25#issuecomment-855423038

**Comment by SteveTheEngineer** [comment]
Closing the issue assuming it has been solved. Please notify me if the issue persists.
