### ISSUE TITLE
Plugin conflicts with Eco

### ISSUE THREAD

**Issue by Swirren** [SteveTheEngineer/SS-Kotlin#2]
![image](https://user-images.githubusercontent.com/64167426/212693431-fe93c36c-6130-4ba5-8886-88f447653835.png)

Link to Eco: https://github.com/Auxilor/eco

I can send latest.log but not sure how much help it would be

**Comment by SteveTheEngineer** [comment]
So, it says it will _likely_ conflict. Does it?

**Comment by Swirren** [comment]
It did, yes. Disabled all plugins relating to eco

**Comment by SteveTheEngineer** [comment]
Try the latest compatibility jar and see if it works. https://github.com/SteveTheEngineer/SS-Kotlin/releases/1.8.0

**Comment by Swirren** [comment]
An update for Eco seems to fix the problem -FancyDrops doesn't use your Kotlin plugin, it instead pulls from eco itself. Weird, but a fix nonetheless
![image](https://user-images.githubusercontent.com/64167426/212930313-527878cd-c49b-48bf-868c-f683e2a95cb3.png)

**Comment by SteveTheEngineer** [comment]
> An update for Eco seems to fix the problem -FancyDrops doesn't use your Kotlin plugin, it instead pulls from eco itself. Weird, but a fix nonetheless ![image](https://user-images.githubusercontent.com/64167426/212930313-527878cd-c49b-48bf-868c-f683e2a95cb3.png)

Well, that's what the compat version does - it delegates loading kotlin to whatever other plugin is providing it.

**Comment by Swirren** [comment]
I don't have the compat version installed

**Comment by SteveTheEngineer** [comment]
> I don't have the compat version installed

Well, it works now because they've probably updated to Kotlin 1.8.0. Anyways, it'll be better if you use the compat version instead.
